import { google } from "googleapis";
import { Readable } from "stream";
import type { MediaType, PostResult } from "@/types";

/**
 * Upload a video (or image as a Short/post) to YouTube.
 * YouTube only accepts video uploads via the Data API.
 * Images are posted as YouTube Community posts (requires channel with 500+ subscribers).
 *
 * Required env vars:
 *   YOUTUBE_CLIENT_ID
 *   YOUTUBE_CLIENT_SECRET
 *   YOUTUBE_REFRESH_TOKEN  – obtain once via OAuth consent flow
 */
export async function postToYouTube(
  mediaUrl: string,
  mediaType: MediaType,
  caption: string
): Promise<PostResult> {
  const clientId = process.env.YOUTUBE_CLIENT_ID;
  const clientSecret = process.env.YOUTUBE_CLIENT_SECRET;
  const refreshToken = process.env.YOUTUBE_REFRESH_TOKEN;

  if (!clientId || !clientSecret || !refreshToken) {
    return { platform: "youtube", success: false, error: "YouTube credentials not configured" };
  }

  if (mediaType === "image") {
    return {
      platform: "youtube",
      success: false,
      error: "YouTube does not support image uploads via API. Use video only.",
    };
  }

  try {
    const oauth2Client = new google.auth.OAuth2(clientId, clientSecret);
    oauth2Client.setCredentials({ refresh_token: refreshToken });

    const youtube = google.youtube({ version: "v3", auth: oauth2Client });

    // Download the video
    const mediaRes = await fetch(mediaUrl);
    if (!mediaRes.ok) throw new Error(`Failed to download video: ${mediaRes.status}`);
    const mediaBuffer = Buffer.from(await mediaRes.arrayBuffer());

    const title = caption ? caption.slice(0, 100) : "JPT Generated Video";
    const description = caption || "Generated by JPT Media Bot";

    const uploadRes = await youtube.videos.insert({
      part: ["snippet", "status"],
      requestBody: {
        snippet: {
          title,
          description,
          tags: ["AI", "generated", "JPT"],
          categoryId: "22", // People & Blogs
        },
        status: {
          privacyStatus: "public",
          selfDeclaredMadeForKids: false,
        },
      },
      media: {
        mimeType: "video/mp4",
        body: Readable.from(mediaBuffer),
      },
    });

    const videoId = uploadRes.data.id;
    const postUrl = videoId ? `https://www.youtube.com/watch?v=${videoId}` : undefined;
    return { platform: "youtube", success: true, postUrl };
  } catch (err) {
    return { platform: "youtube", success: false, error: String(err) };
  }
}
